# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gorilla' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gorilla
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'ReactorKit'

  target 'GorillaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GorillaUITests' do
    # Pods for testing
  end

end
