# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gorilla' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gorilla
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'ReactorKit'
  pod 'ReusableKit/RxSwift'
  pod 'Kingfisher', '~> 5.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'LoggerKit'
  pod 'SegementSlide', '3.0.0'
  pod 'FloatingPanel'
  pod 'PanModal'
  pod 'SwiftyUserDefaults', '~> 5.0'

  target 'GorillaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GorillaUITests' do
    # Pods for testing
  end

end
